# Generated by Django 2.0.2 on 2018-03-06 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20180306_0639'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_picture',
            field=models.FileField(default='ToyStory.jpg', upload_to=''),
        ),
    ]
