# Generated by Django 2.0.2 on 2018-03-06 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_movie_movie_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_picture',
            field=models.FileField(upload_to=''),
        ),
    ]
