# Generated by Django 2.0.2 on 2018-03-06 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20180306_0713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_picture',
            field=models.CharField(max_length=1000),
        ),
    ]
