# Generated by Django 2.0.2 on 2018-03-08 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='available',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='price',
        ),
    ]
