# Generated by Django 2.0.2 on 2018-03-08 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_auto_20180308_0134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='seat',
            field=models.IntegerField(default=1),
        ),
    ]
