# Generated by Django 2.0.2 on 2018-03-08 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_auto_20180308_0350'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='type',
            field=models.CharField(choices=[('NA', 'NONE'), ('ST', 'Student'), ('AD', 'Adult'), ('SR', 'Senior')], default='NA', max_length=2),
        ),
    ]
