# Generated by Django 2.0.2 on 2018-03-09 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_auto_20180308_2259'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('movie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Movie')),
            ],
        ),
        migrations.AlterField(
            model_name='ticket',
            name='type',
            field=models.CharField(default='NA', max_length=10),
        ),
    ]
