# Generated by Django 2.0.2 on 2018-03-11 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_auto_20180311_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
