# Generated by Django 2.0.2 on 2018-03-12 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_shoppingcart_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='review',
            name='movie',
        ),
        migrations.DeleteModel(
            name='Discount',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
